### ISSUE TITLE
Outdated Rfam information

### ISSUE THREAD

**Issue by kalvari** [geneontology/geneontology.github.io#1]
Rfam is now hosted by EMBL-EBI.
New website URL: http://rfam.org

As of November 2015, a new team has taken over with:
Anton Petrov (Lead)
Ioanna Kalvari (Software Developer)
Joanna Arganiska (Database Curator)

We would really appreciate if you updated the text with the new information and please feel free to contact us if you have any questions.

**Comment by kltm** [comment]
Tagging @suzialeksander -- I'm not sure the best way to follow through with all the necessary repos...

**Comment by cmungall** [comment]
I think this is a one-off change to db-xrefs.yaml

**Comment by pgaudet** [comment]
as well as in https://github.com/geneontology/go-site/blob/master/metadata/group-contacts.csv

**Comment by suzialeksander** [comment]
I've updated both the group-contacts.csv and the db-xrefs.yaml. 

@kalvari, I found a GitHub handle for Anton Petrov but not for Joanna Arganiska, can you ask your curator to make one? 
Thanks!

**Comment by kalvari** [comment]
@suzialeksander Many thanks for taking care of this. Joanna is on GitHub as @JoannaArgasinska. Please feel free to let me know if this doesn't work. 
Thank you!

**Comment by suzialeksander** [comment]
Great, I've added you all to the file. Thanks @kalvari !

**Comment by kltm** [comment]
This issue was moved to geneontology/go-site#813
