### ISSUE TITLE
GOC Website Feedback

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#100]
Please write your feedback below

**Comment by jimhu-tamu** [comment]
I'm not a fan of gradient backgrounds.

**Comment by suzialeksander** [comment]
Already on the radar but so it's addressed: 

* We need to fix the headers (shouldn't be blue).  Only hyperlinks should be in blue text.  

* I don't like headers as links.

**Comment by tberardini** [comment]
Help > Contact Us goes to help.geneontology.org whose header circles back to current website, not beta version - change header of that page? go to different page?

**Comment by jimhu-tamu** [comment]
Search should be available in the general header, not just on the home page. Shouldn't have to go back to do another search.

**Comment by goodb** [comment]
The new site looks nice to me.  I'd prefer if it was an integrated single web application rather than a collection of links off to other sites like Amigo and Panther, but understand that is not in the plan.  

I'd like to know how you are quantifying improvements to the user experience.  Do you have Google Analytics or similar?  Can we track user bounces?  Have there been any usability studies done with real users?  How has the restructuring impacted SEO?

**Comment by lpalbou** [comment]
Thanks for the quick feedbacks :)

@tberardini the helpdesk is still link to the current geneontology.org, whenever we switch to the new website, it will be on geneontology.org so the problem will be solved. 

@jimhu-tamu I forgot to mention it but we do have an instant search under menu help / search and it you don't have to switch pages when changing your search

@jimhu-tamu there was also a version with constant navy blue. It more or less ressemble that:
<img width="1631" alt="screen shot 2018-10-17 at 4 15 58 pm" src="https://user-images.githubusercontent.com/24249870/47113828-e0576880-d20e-11e8-8488-345176dc07b5.png">

I personally much more prefer the gradient version, but let's put it to a vote.

@goodb I completely agree, I would prefer a unique site but that's a PI decision. We do have google analytics on the old site, not on the new, but we'll monitor the changes, yes (including bounce rate). SEO is still an ongoing "problem" with some links that will disappear (eg 400 links and now around 32), however there will be redirects and only 50-70 pages are actually viewed on the old site (so that's a good news)

**Comment by jimhu-tamu** [comment]
@lpalbou one problem I have with both the gradient and the solid dark blue is that they make the GO logo less visible. Perhaps an alternative coloring of the logo would work better.  But I'm an old boring guy who likes white backgrounds.

**Comment by pgaudet** [comment]
I agree with @jimhu-tamu that the backgroud doesn't work well with the logo. If you don't want to do white - can some pale grey like we have in AmiGO work ?

**Comment by lpalbou** [comment]
Agreed, I'll create some more proper variations of it - this example was a quick one only to illustrate what it could be, it's not refined

**Comment by lpalbou** [comment]
There has been several work on the design since then, hence I mark this issue as resolved
