### ISSUE TITLE
Dropdown menu inconsistency: "guide"

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#104]
Little inconsistency still- there's a "**_Guide_** to GO Evidence Codes", but also a "GO Subset **_Guide_**" in the drop-downs.

I don't have a preference but would like the "guide" to be consistently before or after... or could we remove the word? (not sure how I feel about that option yet)

**Comment by cmungall** [comment]
I like guide first

**Comment by pgaudet** [comment]
OK, 'Guide' first. @suzialeksander Would you please fix ?

**Comment by suzialeksander** [comment]
Done!

**Comment by pgaudet** [comment]
thanks !
