### ISSUE TITLE
On some systems, text appears thin and without contrast, affecting usability

### ISSUE THREAD

**Issue by kltm** [geneontology/geneontology.github.io#105]
On all pages of the new demo site at https://geneontology.github.io/ , on some systems, the text appears in extremely low contrast and extremely thin, to the point of making the site extremely difficult to read, especially in the menus. Some classes or tags seems to be more affected than others.

Obviously this is not common, and appears to be at least partially system, rather than browser dependent, as the pages seemed to render the same in Firefox (64.0b10 (64-bit)), Chromium (Version 70.0.3538.77 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)), and Google Chrome (Version 70.0.3538.110 (Official Build) (64-bit)).

```
~$:) lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

Examples of the issue:

![scr-2](https://user-images.githubusercontent.com/2687900/48812582-dfbb6180-ece7-11e8-8727-64e19cd81a23.png)
![scr-1](https://user-images.githubusercontent.com/2687900/48812583-dfbb6180-ece7-11e8-8bb6-9bf2fff2ff86.png)

**Comment by lpalbou** [comment]
Thanks @kltm for spotting that out. Ubuntu has a slightly different way to handle font-weight so I have changed that and it's now working correctly on both chrome / firefox & chromium:

<img width="1403" alt="screen shot 2018-12-05 at 11 11 41 am" src="https://user-images.githubusercontent.com/24249870/49537959-2e880000-f87f-11e8-99fd-c1e77662d559.png">

<img width="1398" alt="screen shot 2018-12-05 at 11 15 25 am" src="https://user-images.githubusercontent.com/24249870/49537968-3051c380-f87f-11e8-8d3e-5a22db8ae652.png">
