### ISSUE TITLE
Provide prominent links to GAF format and fix the URL

### ISSUE THREAD

**Issue by cmungall** [geneontology/geneontology.github.io#107]
The URLs
https://geneontology.github.io/docs/go-annotation-file-gaf-format-20/
https://geneontology.github.io/docs/go-annotation-file-gaf-format-21/

was a result of importing into drupal and drupal dropping the period. I have see people actually name the format gaf20/gaf21 in their code. We should introduce a period or dash, and make a 30x permanent redirect.

The links to GAF format are not very prominent. We should add here:

http://current.geneontology.org/products/pages/downloads.html
(this is a go-site pipeline thing rather than website mentioning for completion)

And on the intro to annotations page:
https://geneontology.github.io/docs/go-annotations/

**Comment by pgaudet** [comment]
We had a lot of feedback on this page - http://current.geneontology.org/products/pages/downloads.html

@selewis Do you remember where that ticket is ?

**Comment by pgaudet** [comment]
Found it ! https://github.com/geneontology/go-site/issues/847

**Comment by suzialeksander** [comment]
* [ ] make URL "go-annotation-file-gaf-format-2.1" (or "go-annotation-file-gaf-format-2-1" )
* [ ] make same for "go-annotation-file-gaf-format-20"
* [ ] redirects for both URLs above
* [x] add links to GAF format on https://geneontology.github.io/docs/go-annotations/

@cmungall is the current link to GAF format (for now just 2.1 pending changes mentioned in #106 ) https://test.geneontology.io/docs/download-go-annotations/ sufficient or should that still be made more obvious?

**Comment by cmungall** [comment]
Looks great

We should take this opportunity to fix the URLs for the formats. It is 2.1
not 21. We can make this 2-1 to be more URL canonical. But we will need to
redirect old.

**Comment by suzialeksander** [comment]
Added GAF links to go-annotations page, that's done.  As for the URLs and redirects, from Gitter

> as for changing 21 in 2.1 or 2-1, to change that, I’ll need to check all other references first so don’t change the permalink (adding a redirect would work but that’s bad practice here since this is used as a workaround) 

so assigning @lpalbou

**Comment by suzialeksander** [comment]
@lpalbou If this is as straightforward as it sounds, can you get to it before the meeting? thanks!

**Comment by lpalbou** [comment]
@cmungall @suzialeksander PR solving this: https://github.com/geneontology/geneontology.github.io/pull/161

The urls are now:
* http://geneontology.org/docs/go-annotation-file-gaf-format-2.0/
* http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/

I have checked all internal links to match those and we still have the old redirects for:
* /page/go-annotation-file-gaf-format-20
* /page/go-annotation-file-gaf-format-21
