### ISSUE TITLE
FAQ structure

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#108]
On the old site, we had a main faq page just listing the different questions:
http://geneontology.org/faq-page

And then we had 1 page for each question, e.g. /faq/how-do-i-use-gos-term-enrichment-tool

I think for search optimization (google indexing - SEO), it would probably be a good idea to have the same structure here

@pgaudet @selewis  ?

**Comment by pgaudet** [comment]
It's a bit technical - while it was nice to have separate pages, I don't know why it was done like this.

**Comment by selewis** [comment]
I agree same structure.

One comment. Under 'database' it just talks about the old mysql repository, but there aren't any general questions, such as "how are the GO annotations stored" or "how can the GO be queried". In other words nothing to point people to GOlr, or the GO-CAMS (owl) or Biolink. We need to have information to lead people to the right place.

**Comment by kltm** [comment]
Things like SEO (where things like an index etc. would probably be useful as well) are likely a little farther down the list. After we have a release of the site, we can circle around on these topics more generally.

**Comment by suzialeksander** [comment]
Update: There were plans to make the FAQ integrated into the planned helpdesk app (Tender) so it would be more organized, similar to:
https://help.eyeo.com/en/adblockplus/

However, the Tender app is having issues dealing with GH's recent upgrades ("no timeline" was what we were given); plans to use Tender are on hold until we're certain they're functioning again.

**Comment by lpalbou** [comment]
As the Tender integration will not be happening, what's our plan here ? There are currently 83 FAQs so unless we structure them in categories, an index content would not be really helpful. 

Proposals:
* As a first pass, I can create collapsible titles, this will improve the search and readability of our FAQs (example: https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f)
* Creating categories for those 83 FAQs is probably a good idea to help organize / search FAQs, @suzialeksander could you do it ?

**Comment by suzialeksander** [comment]
The category tags from before are still in the GH markdown, just currently hidden from users on the site.

**Comment by suzialeksander** [comment]
Clean update: possibly collapsing boxes.  This will be part of a new Website projet.  Tagging @pgaudet to add

**Comment by suzialeksander** [comment]
won'tfix
