### ISSUE TITLE
New website needs to support some kind of documentation search

### ISSUE THREAD

**Issue by kltm** [geneontology/geneontology.github.io#115]
Currently, the new website does not have any method of searching within the site/documentation. This is a very common use case and will need to be supported for release.

Most easily, this could be done with a custom search box from google, etc. It may be nice to supply a site.xml as well.

Other (more complicated) methods could be https://lunrjs.com/ , compiled search in jekyll, etc. It may be better to work on something more complete later on in a different ticket.

**Comment by lpalbou** [comment]
@kltm we did the design of the site with the product owners some time ago and they don't want a search bar on the landing page. It was agreed to get access to the search documentation from the menu.

**Comment by kltm** [comment]
Honestly, that seems a bit...idiosyncratic...to me. @suzialeksander What say you?

**Comment by suzialeksander** [comment]
I remember the idea about killing off multiple search boxes.  I'm not positive the current method is ideal. Would there be a way to display a search box for all pages except the homepage?  Honestly I'm about two menu options away from having seen that search option, I've been checking pages individually and I wasn't aware it was there- I've spent about a solid week looking at the site.

@lpalbou, am I reading the algolia site correctly? I looked at the 4 sites they're advertising, and I like the search feature on https://www.birchbox.com/. There's a magnifying glass icon that turns into a search.  Would something like that be up for discussion?

Also- the current search isn't searching live; it's hitting on things I've changed in the past week to past three hours.  Any idea why there's a lag?

**Comment by kltm** [comment]
I just tried https://geneontology.github.io/search and it doesn't seem to be active (work) for me--I input "download" and nothing happens.
I get a bunch of errors like:
```
TypeError: hit._highlightResult.title is undefined[Learn More] search:6936:58
TypeError: hit._snippetResult is undefined[Learn More]
search:6938:41
TypeError: hit._highlightResult.title is undefined[Learn More] search:6936:58
TypeError: hit._snippetResult is undefined[Learn More]
search:6938:41
TypeError: hit._highlightResult.title is undefined[Learn More]
search:6936:58
TypeError: hit._snippetResult is undefined[Learn More]
search:6938:41
TypeError: hit._highlightResult.title is undefined[Learn More] search:6936:58
TypeError: hit._snippetResult is undefined[Learn More]
```

**Comment by suzialeksander** [comment]
I'm on https://test.geneontology.io/search

**Comment by suzialeksander** [comment]
Beyond these error messages, I just can't think of a site I frequently use that doesn't have an obvious search bar in the header.

**Comment by lpalbou** [comment]
@suzialeksander we could show a search box on all pages except the homepage but I am not sure this is intuitive either. Users that come to GO most of the time wants to download, perform an enrichment analysis or browse the ontology / annotations. Each of this use has a clearly designed way to do that. Searching the documentation is something else and is surely not the first use case of GO. It would however always be here in a guide or tutorial section where you expect to have a quick access.

For the effect on birchbox, everything is possible but I strongly advise against creating those kind of effects as GitHub pages are not great to dynamically change the content of pages, as I mentioned several times before. You should see GitHub pages are reading pages of book and not expect a page to change based on your actions.

Yes, the current search is not live, see [my comment above](https://github.com/geneontology/geneontology.github.io/issues/115#issuecomment-454571815). However, we could trigger a reindexing every day for instance or if we use a webhook, at every commit.

@kltm you are correct, download didn't provide any results, but strangely, searching other words like "GAF" works. I may not have indexed the full content of the pages or I might have a JS error, I will check that soon.

**Comment by lpalbou** [comment]
> Beyond these error messages, I just can't think of a site I frequently use that doesn't have an obvious search bar in the header.

@suzialeksander we want the search bar to be for GO terms and Gene Products, not for the documentation of the site !

**Comment by suzialeksander** [comment]
The "Search GO Documentation": what exactly is it indexing? 

For example, my searches for "Pascale" (https://test.geneontology.io/docs/whoweare/) and "Agbase" (https://test.geneontology.io/docs/annotation-contributors/) don't hit on anything.

**Comment by suzialeksander** [comment]
> Users that come to GO most of the time wants to download, perform an enrichment analysis or browse the ontology / annotations. 

Agreed. All 3 of these are easily accessed from the home page.  But if they're still poking around the site after presumably hitting the homepage, I think it's reasonable to assume they're looking for something else- how to cite, what is this "GO annotation" thing mentioned in a paper I'm reviewing, etc.  

If the search bar can't handle regular site pages in addition to gene products and GO terms (which I think we've settled on that not happening on a GH based site), there should be a way to search the docs.  I like the transient search option or the "all-but-homepage" option for this reason.  

How significant of a technical barrier is there to either option?

**Comment by suzialeksander** [comment]
From gitter with @lpalbou : 
> anyhow, yes I can implement a reindexing at every commit, but not before next week (fully overloaded)

Should solve the above question about lag between edits & results.

**Comment by suzialeksander** [comment]
Note to check search terms after the index: Currently "licens" and "license" unexpectedly return different results- same pages but the results text is different.

**Comment by kltm** [comment]
Note: https://github.com/geneontology/geneontology.github.io/pull/120

**Comment by lpalbou** [comment]
> Note to check search terms after the index: Currently "licens" and "license" unexpectedly return different results- same pages but the results text is different.

I don't really think that's important since 1) a user is expected to enter a complete word and 2) the result pages are good

I'll let this issue opened until we have some system to automatically update the index

**Comment by lpalbou** [comment]
Closing this ticket for the moment as the search page is working and also included in 404 search page https://github.com/geneontology/go-site/issues/978
