### ISSUE TITLE
"Help" in top menu needs kerning

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#118]
_From @suzialeksander on January 17, 2019 20:35_

@lpalbou I believe you fixed something similar on the GO-CAM site quite easily?

_Copied from original issue: geneontology/go-site#980_

**Comment by lpalbou** [comment]
I am not sure I see what you mean ?

The letter spacing for the menu items is on purpose for improved readability

**Comment by suzialeksander** [comment]
I was referring to how "Downloads" and other options look wonky, appears to be "D  o  w  n  l  o  a  d  s" but "Help" looks normal.  If that's intentional, why would people need to be able to read "Help" but not need to easily read "Downloads"?  Can't we just make all the options look the same?

**Comment by lpalbou** [comment]
1. this was discussed with Suzy L. that we wanted to have letter spacing on menu items to improve readability, but you're right, "Help" was missing a style
2. I also decreased this letter-spacing slightly
