### ISSUE TITLE
Links from most recent NAR paper should work on new site

### ISSUE THREAD

**Issue by cmungall** [geneontology/geneontology.github.io#127]
Our NAR paper https://academic.oup.com/nar/article/47/D1/D330/5160994

has a link to:
http://geneontology.org/page/acknowledgments-contributors

But the corresponding page cannot be found:
https://test.geneontology.io/page/acknowledgments-contributors

It might be an idea to check all GO NAR papers for links

**Comment by suzialeksander** [comment]
http://geneontology.org/page/acknowledgments-contributors should redirect to https://test.geneontology.io/docs/annotation-contributors/

@lpalbou @kltm was this page on the list of redirect links?

**Comment by suzialeksander** [comment]
http://www.geneontology.org/page/go-subset-guide- new should be ok, https://test.geneontology.io/docs/go-subset-guide/ 

@lpalbou @kltm Is there a way for the other papers to be automatically checked?

**Comment by lpalbou** [comment]
@suzialeksander yes there is, but it's usually not 100% accurate. We discussed it some time ago and we could do something like the following:

First Query to PubMed to retrieve all PMIDs for a given author:
```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pmc&term=Chris+Mungall%5Bauthor%5D&RetMax=1000
```

Second Query to PubMed to get metadata about X (comma separated) articles:
```
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=pmc&id=5774126,3105495&retmode=json
```

However, once again, even if we can do anything with everything, we are supposed to avoid any dynamic content on the GO site, Jekyll/GitHub pages were not made for this.

**Comment by kltm** [comment]
@lpalbou There is nothing wrong with small pieces of JS to enhance, Jekyll templates to files, and/or pushing things into GH. We just need to work out the overall details about what we want to do.

**Comment by cmungall** [comment]
I'm not sure why we're discussing queries? In the meantime the links I highlighted continue to be broken

**Comment by lpalbou** [comment]
@cmungall it's now corrected. Not however this link was ranked 260 with a single view / month on google analytics. We only redirect the top 75 links with at least 10 views / month.

@kltm yes there is and that's why frameworks create a level of abstraction to avoid direct manipulation of the DOM through JS. But let's avoid this discussion again.
