### ISSUE TITLE
information to add to collaborations page

### ISSUE THREAD

**Issue by selewis** [geneontology/geneontology.github.io#129]
1. Include RO (and other ontologies) in the table of related ontologies
2. Include another column in this table for other resources that also use the same ontology (e.g. GTEX and EoL and ENCODE for Uberon and Cell Type)

cc @cmungall

**Comment by selewis** [comment]
Not essential for the initial release, but would be nicer to have it.

**Comment by lpalbou** [comment]
@cmungall could you check this PR ? https://github.com/geneontology/geneontology.github.io/pull/157

I didn't had time however to check where those ontologies are currently used and it would take more time without being exhaustive..
