### ISSUE TITLE
duplicated ontology table on collaborations and annotation-contributors pages

### ISSUE THREAD

**Issue by selewis** [geneontology/geneontology.github.io#130]
Which, of course, will make maintenance more a pain and at risk of discrepancy. So pick one as the primary (I think on the collaborations page), replace the duplication with a link to the primary.

**Comment by selewis** [comment]
As previously none of these issues should keep the updated site from being released

**Comment by suzialeksander** [comment]
Example: 

http://geneontology.org/docs/collaborations/ lists "Integration with other ontologies" (including PRO, PO, ECO, etc)

http://geneontology.org/docs/go-consortium/ lists "Current GO Consortium contributing groups" (including PRO) as well as "Ontologies imported by the GO Consortium" (PO, ECO, etc.)


@pgaudet can we discuss what should go where? I'm leaning toward merging "Ontologies imported by the GO Consortium" in to the existing table on http://geneontology.org/docs/collaborations/

**Comment by lpalbou** [comment]
@suzialeksander I think the question behind is: are the ontologies we import considered as collaborations ? It seems more like a technical specification to me and if it is, I would remove that table both from [collaborations](http://geneontology.org/docs/collaborations/) and [go-consortium](http://geneontology.org/docs/go-consortium/) and insert it in our [ontology-documentation](http://geneontology.org/docs/ontology-documentation/)

@cmungall @pgaudet opinion ?

**Comment by suzialeksander** [comment]
Move to Manager's agenda 20 Aug 2019, ask Paul/Chris to call out most used ontologies vs. less used
