### ISSUE TITLE
brand new GO.org redirects to https://geneontology.github.io/docs/ on some links

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#132]
From http://geneontology.org/docs/go-annotations/ , the very last links (to the GAF page and GPAD) redirect to wrong domain- https://geneontology.github.io/

**Comment by lpalbou** [comment]
@suzialeksander can you double check that as I don't have this behavior on my laptop. I am guessing bad cache / cookie, try another browser maybe ?

**Comment by suzialeksander** [comment]
Ah.  Yes, I fixed these they were hard coded in.  Is there a way to check the other pages or do I have to do that manually too?

**Comment by lpalbou** [comment]
I searched for it in the repo and there are no other links to geneontology.github.io, so we should be fine
