### ISSUE TITLE
Enrichment options from GO home page seem to be "sticky"

### ISSUE THREAD

**Issue by kltm** [geneontology/geneontology.github.io#135]
From @ValWood

Also the enrichment options from The GO home page seem to be "sticky"

The first time I visited I got choices to do different tyes of analyses. Now whatever I do, it always things I want to do the "statistical overrepresentation option" and I don't see any other choices.....

Originally from:
https://github.com/geneontology/panther-enrichment/issues/10#issuecomment-462845556

**Comment by lpalbou** [comment]
@kltm I answered directly in the original post, thanks for pointing it out. Still not sure what this means so waiting to get more information from Val.

**Comment by lpalbou** [comment]
Closing this issue but we still have geneontology/panther-enrichment#10 (comment) where the discussion is going towards giving the choice to do an EA on different closures.
