### ISSUE TITLE
Update FlyBase funding details

### ISSUE THREAD

**Issue by hattrill** [geneontology/geneontology.github.io#136]
For https://geneontology.github.io/docs/annotation-contributors/

In the text for FlyBase:
"National Human Genome Research Institute at the U.S. National Institutes of Health P41 HG000739 and Medical Research Council, UK grant G1000968"

Could you please update the FlyBase funding details by substituting grant G1000968 with grant MR/N030117/1

Thanks

**Comment by lpalbou** [comment]
Corrected here: https://github.com/geneontology/geneontology.github.io/commit/e26084b1402d38ff5d0b14d5dcf77666742300d7
