### ISSUE TITLE
Redirect https to http for the time being

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#139]
It's been a bit confusing some time as whenever I try https://geneontology.org I get a 404. For the time being, any https should be redirected to http. Could you do that @kltm ? Thanks

e.g. https://www.siteground.com/kb/redirect-from-https-to-http/

**Comment by kltm** [comment]
HTTPS to HTTP is considered to be highly dubious behavior, let's focus on getting the HTTPS available properly. It's not like we had HTTPS before anyways so this is not new behavior.

**Comment by kltm** [comment]
(I would also add that I looked into it already and it makes the configurations quite nasty.)

**Comment by lpalbou** [comment]
@kltm I am not saying that's a best practice and everything should be (and will be) in https. You know I have been advocating for it for a long time. But for the time being, anyone entering https instead of http or letting the browser use a default https when not entering the prefix protocol, will get a 404..
