### ISSUE TITLE
Ontology URI for oboInOwl is no longer valid 

### ISSUE THREAD

**Issue by johannes-darms** [geneontology/geneontology.github.io#142]
The go.owl[1] export defines a curie for oboInOwl[2]. Sadly the referenced URI[3] is no longer accessible via HTTP. The new website returns a 404. 

[2]
```
xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#"
```

[1] http://purl.obolibrary.org/obo/go.owl

[3]http://www.geneontology.org/formats/oboInOwl#

**Comment by kltm** [comment]
@cmungall Should oboInOwl be moved into the release process (as part of the general migration away from SVN)?

**Comment by cmungall** [comment]
No, static file

**Comment by kltm** [comment]
Discussed with @cmungall , will place in `go-ontology`/contrib

**Comment by kltm** [comment]
URL should now resolve.
