### ISSUE TITLE
EA on GO homepage- icon misleading

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#143]
The three bars next to "example" is a menu icon, but this isn't a menu.  Perhaps no icon, or just a little circular refresh icon to indicate there are multiple lists that can be loaded?

**Comment by lpalbou** [comment]
@suzialeksander that's how you represent lists. I would never guess that a circular icon indicate multiple lists

**Comment by suzialeksander** [comment]
As far as users go, I would suspect many see the hamburger button.  I was just suggesting a "refresh" icon as an alternative since you can't choose a specific list here- it's more like you're refreshing the option.  Maybe the solution is no icon then.

**Comment by pgaudet** [comment]
Not critical

**Comment by pgaudet** [comment]
OK, logo was removed
