### ISSUE TITLE
EA "examples" are not clearly human

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#144]
On the EA interface on http://geneontology.org/, there's an option to load examples.  However, it's not clear this is a human list only- should perhaps clear itself if you pick an organism after loading the 'examples list', or grey out the Organism drop-down if populated, etc.  Right now it still tries to run the human list (I think that's a human list, not totally sure) regardless of which organism you select in the dropdown.

**Comment by lpalbou** [comment]
@suzialeksander this is not a human list only (e.g. genes up-regulated by activation of hedgehog signaling in rattus), however I do get what you mean.

If I am correct, you are describing two issues:
* have better examples - I have added some examples from msigdb that I thought interesting, but it would be great if our curators could provide us with other examples. We can probably raise this point at the Cambridge meeting

* to restrict the list of species for a specific example is possible but:
  * each gene set examples must then also provide the list of species usable
  * a same gene set if described with gene names could actually also be used on other species
  * dynamic behavior like grey out items in a list is not something we want to do without a framework - this site is technically very simple

**Comment by lpalbou** [comment]
> Right now it still tries to run the human list (I think that's a human list, not totally sure) regardless of which organism you select in the dropdown.

Just to be clear on that, selecting an organism will NOT change the list of examples but it **will** run the EA with the selected organism. 

Launch on **human**:
<img width="753" alt="Screen Shot 2019-03-29 at 4 42 13 AM" src="https://user-images.githubusercontent.com/24249870/55230428-0d0ba500-51dd-11e9-92fa-8361b5effdb9.png">

Launch on **rat**:
<img width="773" alt="Screen Shot 2019-03-29 at 4 42 08 AM" src="https://user-images.githubusercontent.com/24249870/55230450-1a289400-51dd-11e9-93e0-1a987ec0f348.png">

**Comment by suzialeksander** [comment]
OK.  I'll close this as a "won'tfix".  The extra examples are good (more would be better but not a priority).
