### ISSUE TITLE
go-annotations.md GO-Causal Activity Models section too jargony

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#146]
I'm not sure if this is the best place for this, as the rest of this page describes traditional annotations (the Qualifier section is NOT, contributes to, and colocalizes with)- not Noctua qualifiers... hmm.  I'd like to make this page more cohesive and hopefully no longer.  But the GO-CAM section is a little too complicated/advanced- for example, a "standard annotation" is never even defined.

**Comment by lpalbou** [comment]
@suzialeksander it was specifically asked by Paul T. to have this section on GO-CAMs and links to both annotations and GO-CAMs. The text description was also discussed and rewritten as a group consensus and is taken directly from the GO-CAM site. If it needs some rewrite, let's bring the subject to the manager or GO-CAM call. As for "Standard" GO annotation, it is the way we are calling GO annotations in the article and also the GO-CAM site documentation, so I think it's fine.
