### ISSUE TITLE
Documentation for GO archives

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#156]
Hello,

We found this link on the wiki: http://archive.geneontology.org/
(on this page: http://wiki.geneontology.org/index.php/GAF_Storage) 

Is this link useful to put on the website ? 

We only have a link to http://archive.geneontology.org/lite
@cmungall @kltm 

(Once we have the answer to this we can delete the wiki page)

**Comment by cmungall** [comment]
This is from 2009, should be archived

**Comment by pgaudet** [comment]
> This is from 2009, should be archived
Sure

But http://archive.geneontology.org/ is still being updated (files from 2019 there)

**Comment by kltm** [comment]
archive.geneontology.org is the only historical record for the database dumps (mysql) and a few other files. Until we have https://github.com/geneontology/go-site/issues/483 completed, it is the only way to get some files.

**Comment by lpalbou** [comment]
@pgaudet The archive page was updated with the following new section:

## General GO archive
The general GO archive which includes both the ontology and annotations under different formats (including deprecated ones) is available at:
[http://archive.geneontology.org/](http://archive.geneontology.org/)
