### ISSUE TITLE
Add topic to Tools & Guides: Matrix & link

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#162]
After it was mentioned at biocuration, it seems like we should link to the Matrix tool and add a short one-sentence blurb on the Tools & Guides under Curation. It would help curators find it, even though they're not the main audience the site is aimed at.

**Comment by suzialeksander** [comment]
@valwood is the existing link (on http://geneontology.org/docs/tools-overview/) sufficient, or is it more intuitive there be a link on the homepage in the "tools & guides" card?

@lpalbou thanks for adding this in to the overview page, how hard would it be to change the matrix image to be the "absolute step colors" instead of "shade heatmap"?

**Comment by ValWood** [comment]
I think that  link is fine.

I recommend for the image using 
DNA replication,  DNA repair, chromosome segregation, cytoplasmic translation,  amino acid metabolism, transmembrane transport.
(i.e avoid component terms)
This will give "good contrast"  between cells and  slightly more terms will look better,

**Comment by pgaudet** [comment]
@ValWood Can you generate the image you want and send it to @lpalbou for updating ?

**Comment by ValWood** [comment]
Try

![Matrix](https://user-images.githubusercontent.com/7359272/60991307-368ead80-a342-11e9-8311-d4c73cb7eece.jpg)

**Comment by pgaudet** [comment]
@lpalbou Would you please update the figure on http://geneontology.org/docs/tools-overview/ ? 

Thanks, Pascale

**Comment by lpalbou** [comment]
Done: https://github.com/geneontology/geneontology.github.io/commit/e9485e8756a3b6df0a2c2ee36722da0bd9c3683d
