### ISSUE TITLE
file-formats-for-mapping/ formatting issues

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#166]
I don't think this is entirely readable.  Seems like formatting bleed through from previous version, needs to be reworked.

**Comment by lpalbou** [comment]
[This page](http://geneontology.org/docs/file-formats-for-mapping/) is currently not linked to any public page but can be accessed from the search. It describes the gp2protein, gp2rna and gp_unlocalized.

It seems it could be deprecated @pgaudet  ?

**Comment by pgaudet** [comment]
@vanaukenk We archived these in the wiki: 
http://wiki.geneontology.org/index.php/Gp2protein
I think we should delete both from the wiki and from the website. 

Thanks, Pascale

**Comment by suzialeksander** [comment]
Sounds good.  File was id-mapping-files.md, and is now gone from the website.
