### ISSUE TITLE
Tiny typos on http://geneontology.org/docs/introduction-to-go-resource/

### ISSUE THREAD

**Issue by nlharris** [geneontology/geneontology.github.io#169]
While reading http://geneontology.org/docs/introduction-to-go-resource/, I noticed a few tiny issues (mostly punctuation) that I would be happy to fix via PRs, but I can't find the website text (maybe it's not in this repo?).

researchers studying the genome of three model organisms: Drosophila melanogaster (fruit fly), Mus musculus (mouse), and Saccharomyces cerevisiae (brewer’s or baker’s yeast) agreed to work collaboratively
->
researchers studying the genome of three model organisms--Drosophila melanogaster (fruit fly), Mus musculus (mouse), and Saccharomyces cerevisiae (brewer’s or baker’s yeast)--agreed to work collaboratively

The corpus of GO annotations: which are the traceable
->
The corpus of GO annotations, which are the traceable
or
The corpus of GO annotations: the traceable

describe its normal, biological role
->
describe its normal biological role

Whether, genomics, transcriptomics,
->
Whether genomics, transcriptomics,

“Gene Ontology enrichment analysis” are
->
“Gene Ontology enrichment analysis” is
or
“Gene Ontology enrichment analyses” are

**Comment by pgaudet** [comment]
Hi @nlharris 

Thanks for the feedback. The files are here: https://github.com/geneontology/geneontology.github.io/tree/master/_docs

And the intro is this document: https://github.com/geneontology/geneontology.github.io/blob/master/_docs/introduction-go-resource.md

Thanks! Pascale

**Comment by suzialeksander** [comment]
Thanks for these, @nlharris.  Fixed all.
