### ISSUE TITLE
finding AmiGO front page from the GO home page

### ISSUE THREAD

**Issue by ValWood** [geneontology/geneontology.github.io#170]
Is quite difficult to get to AmiGO front page  from the  GO front page.

How does one get to here: http://amigo.geneontology.org/amigo
this is our main tool, it shouldn't be hard to locate.

You can get to a browse link but this isn't the top level entry point. 

Also, I thought the 'geeky' tools and guides was moving to be  replaced by a point to access tools. I have watched people click on this link looking for AmiGO !

The front page should be biologist friendly, it seems to be aimed at informaticians and developers.

The browse annotations link is particularly alarming. This link just dumps you on a page with all annotations but no context...

**Comment by suzialeksander** [comment]
pinging @lpalbou, slightly related to https://github.com/geneontology/geneontology.github.io/issues/134

**Comment by lpalbou** [comment]
> Is quite difficult to get to AmiGO front page from the GO front page.

We changed the labels of the browse links to mention AmiGO

> The browse annotations link is particularly alarming. This link just dumps you on a page with all annotations but no context...

It is the same behavior as in quickgo where you arrive in a page with all annotations (https://www.ebi.ac.uk/QuickGO/annotations)

> Also, I thought the 'geeky' tools and guides was moving to be replaced by a point to access tools. I have watched people click on this link looking for AmiGO !

The guide page provides indeed links to the tools (namely, AmiGO, GO-CAM site, Ribbon and Noctua). This page would however benefit some polishing both in terms of content and readability

**Comment by ValWood** [comment]
> We changed the labels of the browse links to mention AmiGO

I think that will help.  

I> It is the same behavior as in quickgo where you arrive in a page with all annotations (https://www.ebi.ac.uk/QuickGO/annotations)

I guess so.
I  think this is clearer. The person I was sat with was  looking under the "annotations" ,enu for annotations. I think that was the problem. And then , because they could not find annotations under the "annotations" menu they looked for "AmiGO" because this was the name of the tool. It wasn't a naive user either. It might be worth getting a few people (biologists in particular)  who are familiar with GO to perform some very basic tasks.

I still think the tools links are misleading. If you click on the "tools icon"  you get the APIs guide. Maybe the overview would be better here?

**Comment by lpalbou** [comment]
@ValWood I corrected the link of the tools image (see comment on https://github.com/geneontology/geneontology.github.io/issues/134). 

For future reference, I prefer we refer to "icons" as those small images that fit in a line of text and to "images" otherwise (took me some time to understand you meant the link of the image)

**Comment by ValWood** [comment]
Thanks, that's much better entry place to tools  for a biologist or naive user.
I will try to remember the words.
