### ISSUE TITLE
Update PRO on Collaborations page, other issues

### ISSUE THREAD

**Issue by kltm** [geneontology/geneontology.github.io#171]
From user by email:

...looking at the GO "Collaborations" page (http://geneontology.org/docs/collaborations/). There is a link to "PRO Help" that does not work (this is also true of a few other links that go to email-based pages as opposed to mailto:). In any case, rather than link to my email, the link should go to our issue tracker:
http://purl.obolibrary.org/obo/pr/tracker

**Comment by pgaudet** [comment]
@suzialeksander Are you taking care of this?

**Comment by suzialeksander** [comment]
done, commit should have also fixed syngo link and mailtos

**Comment by lpalbou** [comment]
@suzialeksander just a comment, can you try to link your PR/commit to the associated ticket ? Just to organize a little :) 

I think you were referring to those: https://github.com/geneontology/geneontology.github.io/commit/82a620cf9d13e8c31837fd59ab39d26ad2de2e7c and https://github.com/geneontology/geneontology.github.io/commit/7090c4d28b8dca32482742381e902a0ba842f28d
