### ISSUE TITLE
Annotation Guidance links from QuickGO broken

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#173]
On pages like https://www.ebi.ac.uk/QuickGO/term/GO:0030674, the link that previously went to Binding term considerations @ http://geneontology.org/GO.annotation.conventions.shtml#binding and now is broken

We need to find the doc, and let Quick GO know about new link.  Searching for "binding guidelines" in the wiki goes to a 5 year old http://wiki.geneontology.org/index.php/Binding_Guidelines, I don't think this is the same as what we removed from the site?? ~~@pgaudet @vanaukenk do you recall what info the QuickGO site referred users to and if it exists on the wiki?~~

**Comment by suzialeksander** [comment]
Ok, it's here: https://web.archive.org/web/20181127144426/http://www.geneontology.org/page/go-annotation-conventions#binding

Is this on the wiki anywhere? I don't believe it is

**Comment by suzialeksander** [comment]
This documentation seems more in depth than what we planned on putting on the website, but I don't know that we had wanted to drive external traffic (from QuickGO) to the wiki.  Are there users that would access 'annotation guidance' links through QuickGO that aren't curators though? Any arguments against having this doc on the wiki?
@pgaudet @vanaukenk

**Comment by pgaudet** [comment]
@alexsign how are these added in QuickGO ? 

@kltm  Do you know if we have back up of those pages anywhere ? 

The best replacement I know of would be this: 
http://wiki.geneontology.org/index.php/Annotating_binding
but it would be great to look at the previous version of the website to see how it compares. 

Thanks, Pascale

**Comment by kltm** [comment]
@pgaudet The Wayback Machine is probably a good place to start. If necessary, we could spin up a Drupal again, but that would take some fiddling.

**Comment by pgaudet** [comment]
Thanks @kltm 

@alexsign this is where the Binging guidelines are now: 
http://wiki.geneontology.org/index.php/Annotating_binding

You probably also need to update: 
http://wiki.geneontology.org/index.php/Annotating_regulation
http://wiki.geneontology.org/index.php/Annotating_downstream_processes
http://wiki.geneontology.org/index.php/Annotating_ligand-receptor_pathways
http://wiki.geneontology.org/index.php/Response_to_x_annotation_guidelines
http://wiki.geneontology.org/index.php/Apoptosis_Curation_Manual
http://wiki.geneontology.org/index.php/MicroRNA_GO_annotation_manual

Are there other such links ? 

Thanks, Pascale

**Comment by alexsign** [comment]
Hi @pgaudet @ggeorghiou, I'm tagging George to it because the annotation guidance maintained by curators through Protein2GO.

**Comment by ggeorghiou** [comment]
![image](https://user-images.githubusercontent.com/21035247/61224154-f9496780-a715-11e9-927f-6e5703e4e463.png)

![image](https://user-images.githubusercontent.com/21035247/61224176-0403fc80-a716-11e9-9ebf-c4fb75b51c13.png)

These are the annotation guidelines we have in place in P2GO

**Comment by ggeorghiou** [comment]
These are the guidelines we currently have:

![image](https://user-images.githubusercontent.com/21035247/61224294-3f063000-a716-11e9-8e86-baf8f0ddc16b.png)

![image](https://user-images.githubusercontent.com/21035247/61224308-4594a780-a716-11e9-8748-bbcda95fc068.png)

**Comment by pgaudet** [comment]
AFAIK the geneontology.org links are dead; can you please check ? 

Thanks, Pascale

**Comment by ggeorghiou** [comment]
They are indeed dead.

**Comment by pgaudet** [comment]
Can you transfer to the links I listed above (https://github.com/geneontology/geneontology.github.io/issues/173#issuecomment-510368131) ?

**Comment by ggeorghiou** [comment]
Working on replacing the obvious ones now but we are missing some (like annotating to transcription factor activity, Describing enzyme functions that catalyse multi-stage reactions ). If I need to make new guidelines, I need to know how they have to be propagated and what to place in the other fields that are in the pictures above.

**Comment by pgaudet** [comment]
For transcription we have this: 

https://docs.google.com/presentation/d/1hOBMnpHbGyKsOJi-Ah3xhAavzOg2RgM4AXRdGbF8A6M/edit#slide=id.p1

Not sure about the multistage reactions; I think we just give multiple GO annotations ?

**Comment by suzialeksander** [comment]
closing, all mentioned links seem to be addressed at QuickGO
