### ISSUE TITLE
Ribbon sandbox

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#179]
At the Cambridge meeting, I rapidly setup a ribbon sandbox for Ruth and Helen.

The sandbox is currently here: http://ribbon.geneontology.xyz

Action items:
- [x] finish the Alliance development and integration of the intermediary go ribbon (using the data model developed a few months back and able to load hundreds of genes)
- [x] deploy it on the S3 bucket to update http://ribbon.geneontology.xyz
- [ ] organize with @kltm to have a more proper ribbon.geneontology.org
- [ ] link the sandbox from the ribbon doc on the go site (https://github.com/geneontology/geneontology.github.io/issues/21) and having a more proper tools page for go (https://github.com/geneontology/amigo/issues/579)

Notes:
* this is an intermediary version of the ribbon,  the final version (web component), will be delivered around September / October (prior to AGR new release)
* the final version of the go ribbon is linked to the development of the go terms page widget for the alliance: goal is to share the tables to browse annotations across applications to get data and visual consistency (go terms page, go ribbon, possibly a new amigo version)
* tickets for the final go ribbon and go terms page widget are on jira: https://agr-jira.atlassian.net/browse/AGR-1662 and https://agr-jira.atlassian.net/browse/AGR-1663 (requires a jira account)

**Comment by lpalbou** [comment]
@kltm  if you have geneontology.org on route53, it would be great for instance if you could create a s3 bucket ribbon.geneontology.org (hosting site)and redirect this URL to the bucket containing the built version of the ribbon sandbox (currently hosted here: ribbon.geneontology.xyz).

Otherwise, could you create a proxy from ribbon.geneontology.org to ribbon.genenontolgy.xyz ? So we can start linking it in the tools page

**Comment by kltm** [comment]
@lpalbou Let's try and get the priority on this item from @pgaudet .

**Comment by lpalbou** [comment]
Update: a mockup of the sandbox is available here http://www.geneontology.xyz/ribbon.html

**Comment by suzialeksander** [comment]
@kltm is this still an active/planned project?

**Comment by kltm** [comment]
Not at the moment; we can reopen when we have resources.
