### ISSUE TITLE
Reconstructing meeting timeline

### ISSUE THREAD

**Issue by kltm** [geneontology/geneontology.github.io#18]
_From @ValWood on September 13, 2018 20:43_

I was looking for some old meeting minutes to reconstruct a timeline for my thesis:

I wanted to access the minutes for  some old meetings:
ftp://ftp.geneontology.org/go/www/GO.meetings.shtml

Can these documents be reinstated?  (they are an important part of the GO archive).

_Copied from original issue: geneontology/go-site#810_

**Comment by kltm** [comment]
That is just a pointer into the legacy SVN (which was exposed on the web).
trunk/www/GO.meetings.shtml

**Comment by kltm** [comment]
It may be worth discussing if this is wiki material (in which case it is ported out) or public material (port to new site).

**Comment by cmungall** [comment]
@ValWood,  a while ago I rescued what I could in our google drive: https://drive.google.com/drive/u/0/folders/0B8kRPmmvPJU3UFhhLTRjV25SOUk

**Comment by ValWood** [comment]
OK fab, I'll close this . good that it isn't lost...

**Comment by ValWood** [comment]
I can't close...

**Comment by ValWood** [comment]
Lot's missing. There were 2 Bar Harbor meetings before 2010, I was looking for those....

**Comment by cmungall** [comment]
Yes, not sure if they were never added to svn, or if I didn't get everything

the folder structure here is a bit ad-hoc
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/meeting/
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/meeting/consortium/

**Comment by pgaudet** [comment]
These should go on the wiki or in the Google drive/GO meetings.

Le jeu. 13 sept. 2018 à 11:17 PM, Val Wood <notifications@github.com> a
écrit :

**Comment by ValWood** [comment]
all the minutes seem to be here which is good:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/meeting/minutes/

**Comment by pgaudet** [comment]
Looks like the 'missing' meeting minutes are hidden in a folder called 'archive': 
https://drive.google.com/drive/u/0/folders/1FrgP2pGdUsQMAss048Pcgq1KR45Ku4Os

I can simply move these up one directory - ok @ValWood @cmungall ?

**Comment by ValWood** [comment]
fine by me...
