### ISSUE TITLE
Adding redirects from previous publications

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#189]
Based on @pgaudet requirement and two publications:
* https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003343
* https://link.springer.com/protocol/10.1007/978-1-4939-3743-1_4

I have updated the following links (https://github.com/geneontology/geneontology.github.io/pull/188):
* GO.downloads.annotations.shtml -> /docs/download-go-annotations/
* /page/download-annotations -> /docs/download-go-annotations/
* GO.annotation.conventions.shtml -> /docs/go-annotations/
* /page/guide-go-evidence-codes -> /docs/guide-go-evidence-codes/
* GO.evidence.shtml -> /docs/guide-go-evidence-codes/
* GO.contents.doc.shtml -> /docs/ontology-documentation/
* /page/current-go-statistics ->  http://geneontology.org/stats.html

But @kltm will need to redirect this link on the proxy side:
* GO.contacts.shtml -> http://help.geneontology.org

**Comment by kltm** [comment]
@lpalbou Why not just use the redirect functionality?
https://github.com/geneontology/geneontology.github.io/blob/34942a99c5ddaa2727ffab6d66e824d8987b6c13/redirected.md

**Comment by lpalbou** [comment]
I did it for the [stats.html](https://github.com/geneontology/geneontology.github.io/blob/master/stats.html#L5) as the page exists on the website, so the front matter redirect made sense.

Here, we would be creating an empty file GO.contacts.shtml just to add the front matter redirect.. I am not a big fan of multiplying empty files just to enable redirects, but it would work too, yes.

If you prefer it fixed that way instead of proxy link, you can merge that PR and close the ticket: https://github.com/geneontology/geneontology.github.io/pull/190

**Comment by kltm** [comment]
Will do--I think it's definitely better to keep as much as possible out of hidden server configs.
