### ISSUE TITLE
Need consistent headers, footers, styles for all GO pages including Downloads

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#199]
Discussion from https://github.com/geneontology/geneontology.github.io/issues/184:
Problem:
Downloads pages have different styles, different headers/footers, and these are totally independent of main site. See 

http://snapshot.geneontology.org/products/pages/downloads.html
http://current.geneontology.org/products/pages/downloads.html

> ...this is a static page produced by the pipeline and external to the go site (hence the different footer and styling).
> 
> Each dynamic page (e.g. stats or the wanted go-subsets) would need to be coded from scratch since we don't use framework. Still possible but let me know of the priority.

Potential solutions: from @kltm 

> Currently, the downloads are generated in a separate location from the main site. There are a few different ways to make sure the footers are consistent (e.g. common templates).

Potential Timeline: from @lpalbou 

> If it's a 1:1 translation, about 2 days. It we want to make it exactly what we want, around 4-7 days between the discussions and iterative coding.

>I liked for instance some of the features of this site and the easy access / description of each annotation set: https://git.dhimmel.com/gene-ontology/ , but this would require us to store additional files in the release.

**Comment by suzialeksander** [comment]
@lpalbou do you have time to discuss or work on this soon? There are a lot of items on the Downloads header dropdown that go to pages that no longer exist.  If we could at lease remove those dead links it would be great.

**Comment by lpalbou** [comment]
@suzialeksander my bandwidth is currently very limited. Should be better next week. This ticket is about the consistency of headers & footers, not broken links. If there are broken links, could you list them in a separate tickets and we can do a quick fix ? Thanks

**Comment by suzialeksander** [comment]
OK, great, this isn't the highest priority at all.  I'll list the links, thanks

**Comment by pgaudet** [comment]
I edited the geneontology.org. I dont know where to edit the 2 mentioned here: 

http://snapshot.geneontology.org/products/pages/downloads.html
http://current.geneontology.org/products/pages/downloads.html

**Comment by kltm** [comment]
@pgaudet Depending on what you're trying to do: https://github.com/geneontology/go-site/blob/0548392c2c9321e241bc973a7939a1dd70a57149/scripts/downloads-page-template.html#L257

**Comment by suzialeksander** [comment]
This should be closable if https://github.com/geneontology/go-site/pull/1990 works
