### ISSUE TITLE
Mine all FAQs into one .md file

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#2]
@kltm can you (easily) add the FAQs to a single file into geneontology/go-docs/documentations as discussed? I can pretty them up/sort/etc. later.

Thanks

**Comment by kltm** [comment]
```
http://geneontology.org/all-faqs
pandoc --from=html --to=markdown_github all-faqs > faqs.md
```

**Comment by kltm** [comment]
Something to start with anyways.

**Comment by suzialeksander** [comment]
Thanks!
