### ISSUE TITLE
Examples in EA box will not load 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#252]
Found by PANTHER, but I can reproduce (I'm on FF 76.0).  From EA tool on http://geneontology.org/
> If I enter some IDs, and then delete them, the Examples won't populate, even after I refresh the page. It only works on the newly launched page.

tagging @lpalbou as I think he added these examples? Is this fixable?

**Comment by lpalbou** [comment]
Just confirmed that. Should be an easy fix, will look into it. Thanks

**Comment by lpalbou** [comment]
Fixed: https://github.com/geneontology/geneontology.github.io/commit/e515f109b53b36ff83739749dc84321c072d9026
