### ISSUE TITLE
Some old broken links

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#254]
I checked the Google Analytics of the GO site this morning and there were still some access (about 500 over 3 months) for each of these old URLs. I added some redirects:

- /GO.slims.shtml -> go-subset-guide.md
- /GO.downloads.database.shtml -> downloads.md
- /GO.downloads.ontology.shtml -> download-ontology.md
- /GO.evidence.shtml -> guide-go-evidence-codes.md
- /GO.ontology.structure.shtml -> ontology-documentation.md
- /GO.tools.shtml -> tools-guide.md
- /GO.database.shtml -> introduction-go-resource.md
- /GO.doc.shtml -> introduction-go-resource.md (could be more wiki.geneontology.org ?)

**Comment by pgaudet** [comment]
Thanks ! Should this be closed ?

**Comment by lpalbou** [comment]
If those forwards look all good to you, yep. I wasn't sure for GO.doc.shtml and GO.database.shtml .
