### ISSUE TITLE
Add SAB to website

### ISSUE THREAD

**Issue by nlharris** [geneontology/geneontology.github.io#257]
Most organizations like to brag about the amazing, accomplished people on their SAB. Shouldn’t GO?

I couldn’t find a list of SAB members anywhere—I would have expected it to be on http://geneontology.org/docs/whoweare/ or somewhere else on geneontology.org. Is this something that should be added (or, if it exists, made more findable)?

I asked about this in 2019 but nothing has happened so I thought maybe I should make a ticket. I was reminded of this issue because I'm helping with a grant proposal that mentions SABs of other ontology resources.

**Comment by lpalbou** [comment]
This sounds reasonable, @pgaudet @suzialeksander ?

**Comment by suzialeksander** [comment]
We don’t currently have this information available. I think it would fit either right after PIs on The Who We Are page, or after current GO contributors? That may bury it a bit more than we want.

**Comment by nlharris** [comment]
You could either create a new page for the SAB or add it to the Who We Are page with an anchor so you can link directly to that part of the page. In either case, I think there should be a menu item under "About" pointing to it.

**Comment by pgaudet** [comment]
I'll bring this up at the PI call today.

**Comment by pgaudet** [comment]
PIs dont think this is necessary. Also the SAB changes regularly, so it's easier not to maintain this.
