### ISSUE TITLE
corrections for 'Relations in the Gene Ontology' page

### ISSUE THREAD

**Issue by balhoff** [geneontology/geneontology.github.io#263]
There are a couple changes to make to this page: http://geneontology.org/docs/ontology-relations/

- Remove chain `'regulates' o 'part_of' -> 'regulates'`
- Add chain `'regulates' o 'regulates' -> 'regulates'`

**Comment by balhoff** [comment]
See https://github.com/geneontology/helpdesk/issues/293

**Comment by pgaudet** [comment]
Oh yes we need to change the images @lpalbou can you please do that ?

**Comment by suzialeksander** [comment]
I don't see these relations anywhere on the page, someone probably removed them although looking quickly in the history I don't see it- reopen if still valid
