### ISSUE TITLE
How many people download GO data per month ?

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#268]
It seems like an important feature to track (even for grants) and I have no idea of the current usage. This would gives us some insights on if users have issues downloading GO data. @thomaspd @cmungall @pgaudet thoughts ?

If we agree it's important, I have no access to the GO AWS, but @kltm should be able to check the get requests stats on both current.geneontology.org and release.geneontology.org S3 buckets : https://docs.aws.amazon.com/AmazonS3/latest/dev/cloudwatch-monitoring.html (or possibly CloudFront reports as I think you cache the data there: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/usage-charts.html).

**Comment by pgaudet** [comment]
I agree it's important. All stats are useful. Do you know how much work is needed to put that in place ?

**Comment by lpalbou** [comment]
Those stats are already tracked by AWS (the 2 links I mentioned) so technically we can already access that data on the GO AWS account - which I don't have access to.

**Comment by cmungall** [comment]
I think the stats will be useful with the caveat that they will be an under-estimation. Many people get GO annotations indirectly from other sources.

**Comment by lpalbou** [comment]
Yep, that's correct; still seems useful to know how many users get GO data from us and if we are getting better or worse over time. In 2021, it would be good to allocate some time to get into contact with the people of bioconductor I mentioned in the past and get at least the "official"/"top" go packages to use the data coming from us.

**Comment by kltm** [comment]
We have not had CloudWatch on the downloads, but have the usual CF console info and buckets `go-data-product-usage-logs/current` and `go-data-product-usage-logs/release` configured to take CF logging. Unfortunately, the script that I used in the past for looking at access (https://github.com/geneontology/go-site/blob/master/scripts/cloudfront-log-lister.js , combined with goaccess.io and some judicious grepping) is currently heaping out, so I need to take a look at that or find a different way to extract the information.

**Comment by kltm** [comment]
Okay, I took two sample months from the CF logs, 2020-04 and 2020-10, and filtered out the comments. With them then joined, I have the following process.

"Data" download I have looking like:
```
cat current-log.txt | grep Hit | grep -v \\.json | grep -v 131\\.243 | grep \\.gaf | wc -l
cat current-log.txt | grep Hit | grep -v \\.json | grep -v 131\\.243 | grep \\.gpad | wc -l
cat current-log.txt | grep Hit | grep -v \\.json | grep -v 131\\.243 | grep \\.gpi | wc -l
cat current-log.txt | grep Hit | grep -v \\.json | grep -v 131\\.243 | grep \\.ttl | wc -l
```
"Ontology" download I have looking like:
```
cat current-log.txt | grep Hit | grep -v \\.json | grep -v 131\\.243 | grep \\.obo | wc -l
cat current-log.txt | grep Hit | grep -v \\.json | grep -v 131\\.243 | grep \\.owl | wc -l
```
The math was done on `release-log.txt.gz` and `release-log.txt.gz` in public bucket `go-data-product-experimental` (if anybody wants to try a hand at it). With all this...

Current data downloads per month:
`(/ (+ 7012 114 109 44) 2.0) ~ 3600+/m`

Release data downloads per month:
`(/ (+ 330 9 4 44) 2.0) ~ 200/m`

Current ontology downloads per month:
`(/ (+ 39804 8573) 2.0) ~ 24000/m`

Release ontology downloads per month:
`(/ (+ 252 369) 2.0) ~ 300/m`
