### ISSUE TITLE
go-stats page not working on safari 14.0.2

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#286]
http://geneontology.org/stats.html

The page works fine on OS X / chrome & firefox but doesn't work on Safari.

It seems to be a CORS issue: 

![Screen Shot 2021-05-17 at 5 09 44 PM](https://user-images.githubusercontent.com/24249870/118571344-adf9a900-b732-11eb-9a38-21d148faa91c.png)

@kltm could you double check the settings of the S3 for current.geneontology.org ? on a public S3 like that I would activate CORS for *, but at least for geneontology.org

**Comment by kltm** [comment]
Interesting--good find! It turns out that there was a difference in the S3 settings with current compared to the others.
The S3 CORS settings on current are now:
```json
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```
It may take a little for it to purge; I'll start an invalidation.

**Comment by lpalbou** [comment]
Great, it's now working 👍 

![Screen Shot 2021-05-17 at 6 07 03 PM](https://user-images.githubusercontent.com/24249870/118575166-afc76a80-b73a-11eb-8cc6-6da91ed58bf7.png)
