### ISSUE TITLE
GO Archive back to old UI

### ISSUE THREAD

**Issue by lpalbou** [geneontology/geneontology.github.io#291]
I saw the GO release 5mn ago and the GO Archive is currently showing with the old UI:
http://release.geneontology.org/

![image](https://user-images.githubusercontent.com/24249870/122708097-3d054f80-d210-11eb-8475-5e2b46811bd8.png)

It's either a new bug somewhere, or I was too quick to check after the release and the script to populate the index.html hasn't been executed yet ? It should be however be executed before the release and be part of the zenodo release.

@kltm

**Comment by lpalbou** [comment]
Interestingly, old release still have the new UI:
http://release.geneontology.org/2021-05-01/index.html

So the index has not been copied to the root http://release.geneontology.org/ and has not been copied to the new release folder: http://release.geneontology.org/2021-06-16/index.html

As a reminder, the same index.html should also be copied to all repositories at every release on current.geneontology.org.

Thanks

**Comment by kltm** [comment]
The lag on release is part of the current finalization code (changing that is in the roadmap). This is now updated.
