### ISSUE TITLE
download-ontology.md "Legacy Downloads" needs to be updated to reflect current infrastructure

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#3]
/documentations/download-ontology.md

has misleading information about the legacy downloads being supported; this is misleading to current users

https://github.com/geneontology/helpdesk/issues/154

**Comment by suzialeksander** [comment]
Looking at this again, do we have *any* links on the new site to archived ontology/annotation files?? I don't see any, and am not sure of where these archived files live now.  I can update the pages if there are links to add

@kltm

**Comment by kltm** [comment]
The "deep" archive still lives at archive.geneontology.org. For the new system, all references to "historical" stuff ("historical" as we do not have a lot of history yet) should point to release.geneontology.org. By and large, legacy downloads (the obo-xml and mysql dumps) should probably not be mentioned, except in passing, such as "for legacy data (e.g. OBO-XML and MySQL dumps) from 2017 and before, access is still currently available at http://archive.geneontology.org" or something.

**Comment by kltm** [comment]
Or...I /think/ this is what you're asking?

**Comment by suzialeksander** [comment]
Yes, that was mostly it.  I was looking for, say, a GAF from May 2014 or something.  Would that be in the assocdb files? 
> For legacy data (e.g. OBO-XML and MySQL dumps) from 2017 and before, access is available at http://archive.geneontology.org

I'd like to add this on https://geneontology.github.io/docs/downloads/, does that seem like the best place? @kltm @pgaudet

**Comment by kltm** [comment]
@suzialeksander Well...actually, not really.
Until rather recently, the pipeline worked by people checking files in to SVN, where they would be munged and them re-checked in to SVN, where the pipeline would take over. Therefore, the true record of these earlier files is the SVN repository, which is not particularly user-friendly (and one of the reasons we've switched over to the DOIed system we have now). As far as I know, the ways to access this are:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ (web)
http://geneontology.org/page/svn-help (cli)
So, this would seem to start to point at having a more nuanced legacy/historical description on the website somewhere--it seems that we'll have trouble for the moment papering over some of this.

It's important to note internally that getting rid of the need to have the SVN around is in the roadmap (ticket around here somewhere), but we have to write docs for what we have, not how we're going to fix it.
