### ISSUE TITLE
Update download-mappings.md

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#31]
Hi Suzi, 

- [x] The download-mappings.md page is missing the links (where 'txt' is); can you add those in ? 

Thanks, Pascale

**Comment by pgaudet** [comment]
- [x] Also, please fix link: 

"More details can be found in the external mapping file format guide."
goes to 

> http://geneontology.org/page/external-mapping-file-format

it should go to 

> _docs/external-mapping-file-format.md

Thanks

**Comment by suzialeksander** [comment]
E. coli Genome and Proteome (GenProtEC) does not seem to be active anymore.  Do I delete link to GenProtEC but leave the txt? 
* (GenProtEC) http://genprotec.mbl.edu/

* Same for MultiFun: genprotec.mbl.edu/files/MultiFun.html

* Same for all JCVI links (EGAD, TIGRFAM, JCVI roles):
 * https://www.jcvi.org/cms/research/projects/tdb/overview/
 * http://www.jcvi.org/cms/research/projects/tigrfams/overview/
 * http://cmr.jcvi.org/cgi-bin/CMR/RoleIds.cgi

**Comment by suzialeksander** [comment]
Same for MultiFun:
genprotec.mbl.edu/files/MultiFun.html

**Comment by suzialeksander** [comment]
Same for EGAD:
https://www.jcvi.org/cms/research/projects/tdb/overview/

**Comment by suzialeksander** [comment]
SMART- I updated the reference to a 2017 paper that's actually on SMART (was 2009 Interpro).  Let me know if this isn't what we want.
OLD:
>Citation: Hunter S, Apweiler R, Attwood TK, Bairoch A, Bateman A, Binns D, Bork P, Das U, Daugherty L, Duquenne L, Finn RD, Gough J, Haft D, Hulo N, Kahn D, Kelly E, Laugraud A, Letunic I, Lonsdale D, Lopez R, Madera M, Maslen J, McAnulla C, McDowall J, Mistry J, Mitchell A, Mulder N, Natale D, Orengo C, Quinn AF, Selengut JD, Sigrist CJ, Thimma M, Thomas PD, Valentin F, Wilson D, Wu CH, Yeats C. InterPro: the integrative protein signature database. Nucleic Acids Res.. Jan 2009;37(Database issue):D211–5. <br>[ [PMID:18940856](http://www.ncbi.nlm.nih.gov/pubmed/18940856) \| [doi:10.1093/nar/gkn785](http://dx.doi.org/10.1093/nar/gkn785)


New:
>Citation: Letunic I, Bork P; 20 years of the SMART protein domain annotation resource. Nucleic Acids Res.. Jan 2018;46(D1):D493–D496. <br> [ [PMID:29040681](http://www.ncbi.nlm.nih.gov/pubmed/29040681) \| [doi.org/10.1093/nar/gkx922]( https://doi.org/10.1093/nar/gkx922)

**Comment by suzialeksander** [comment]
UniProt citation paper also updated to 2015 GOA paper.

**Comment by suzialeksander** [comment]
@kltm @pgaudet  The UM-BBD (enzyme, pathway, reaction IDs) are all broken.  According to https://metacyc.org/MetaCycUserGuide.shtml#TAG:__tex2page_sec_10.2
>The data is now hosted at the Swiss Federal Institute of Aquatic Science and Technology and the database is known as the EAWAG Biocatalysis/Biodegradation Database. http://eawag-bbd.ethz.ch/

Our output says "Generated 2018-10-01", but still uses "UM-BBD_enzymeID" prefix.  Should this now be EAWAG-BBD?

**Comment by pgaudet** [comment]
According to QuickGO, the list of 'with/from' identifiers is: 
- [ ] AGI_LocusCode Arabidopsis Genome Initiative (no IEA)
- [ ] CGD Candida Genome Database  (no IEA)
- [ ] ComplexPortal Complex Portal database of macromolecular complexes  (no IEA)
- [x] EC Enzyme Commission > http://geneontology.org/external2go/ec2go
- [ ] EMBL EMBL Nucleotide Sequence Database  (no IEA)
- [ ] EcoGene EcoGene Database of Escherichia coli Sequence and Function  (no IEA)
- [ ] FB FlyBase  (no IEA)
- [ ] FlyBase FlyBase (Ensembl IEAs)
- [ ] GO Gene Ontology Database > 22M IEAs ->  interontology links ? 
- [ ] GeneDB GeneDB (no IEA)
- [ ] HGNC HUGO Gene Nomenclature Committee (no IEA)
- [x] InterPro InterPro database of protein domains and motifs
- [ ] MGI Mouse Genome Informatics (no IEA)
- [ ] NCBI_gi NCBI databases (no IEA)
- [ ] PANTHER Protein ANalysis THrough Evolutionary Relationships Classification System (no IEA, only IBA)
- [ ] Pfam Pfam database of protein families (no IEA)
- [ ] PomBase PomBase (Ensembl IEAs)
- [ ] RGD Rat Genome Database (Ensembl IEAs)
- [ ] RNAcentral RNAcentral (no IEA)
- [ ] RefSeq RefSeq
- [x] Rfam Rfam database of RNA families
- [ ] SGD Saccharomyces Genome Database
- [ ] TAIR The Arabidopsis Information Resource
- [x] UniPathway UniPathway
- [ ] UniProtKB Universal Protein Knowledgebase
- [x] UniProtKB-KW UniProt Knowledgebase keywords
- [x] UniProtKB-SubCell UniProt Knowledgebase Subcellular Location vocabulary
- [ ] UniRule Manually curated rules for automatic annotation of UniProtKB unreviewed entries ??
- [ ] WB WormBase database of nematode biology
- [ ] WormBase WormBase database of nematode biology
- [ ] ZFIN Zebrafish Information Network
- [ ] dictyBase dictyBase
- [ ] ensembl Ensembl database of automatically annotated genomic data
- [ ] protein_id DDBJ / ENA / GenBank

So, anything not in there we can remove.

**Comment by pgaudet** [comment]
Updated page to split mappings (now called x-references) done in the ontology, versus those done by external groups.
