### ISSUE TITLE
Link to PIR website from GO Subsets page needs updating

### ISSUE THREAD

**Issue by nataled** [geneontology/geneontology.github.io#310]
On this page:
http://geneontology.org/docs/download-ontology/#subsets

The link to PIR within:
<html><body>

Protein Information Resource subset | PIR | goslim_pir
-- | -- | --

</body>
</html>

Is currently:
https://pir.georgetown.edu/

But should be:
https://proteininformationresource.org/

**Comment by pgaudet** [comment]
Fixed, thanks for reporting this
