### ISSUE TITLE
Clean up GOlr -related mentions on "Programmatic Access to Gene Ontology" page

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#314]
http://geneontology.org/docs/tools-guide/

GOlr is not meant to be exposed to outside developers, only the GO API, but we still have it in our official docs. The choice is to either fix the docs first or to point people to the API. The latter is less nice, but more correct.

**Comment by suzialeksander** [comment]
tagging @kltm if you're interested

**Comment by kltm** [comment]
@suzialeksander Yes, I'm very happy to help out in cleaning the documentation.

**Comment by kltm** [comment]
Talked to @cmungall and have enough information now to clean a little.

**Comment by kltm** [comment]
Categorizing under Alliance Software Support as that's what precipitated needing a little cleaning; should be fast.

**Comment by kltm** [comment]
With the merge from @suzialeksander , there should no longer be golr-related references (and less documentation overall given our current supported roadmap).
