### ISSUE TITLE
Rename go-file-format-guide.md? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#34]
Hi @kltm 
Can we rename go-file-format-guide.md
to go-**ontology**-file-format-guide.md

(to more clearly distinguish it from the go-annotation file format ? 

Thanks, Pascale

**Comment by lpalbou** [comment]
Yes we can: https://github.com/geneontology/go-docs/pull/37

**Comment by lpalbou** [comment]
https://github.com/geneontology/go-docs/compare/master...renaming-go-file-format-guide.md?quick_pull=1

**Comment by cmungall** [comment]
how are we handling redirects?

It would be good to do a concerted renaming of certain pages. E.g. the gaf format pages don't make sense since drupal lost the period separating major and minor versions. But we should only do this if we have the redirects under version control.

**Comment by kltm** [comment]
Certain redirects can easily be done within the repo; e.g.: https://github.com/geneontology/go-docs/blob/master/docs/redirected.md 
As discussed for others, we'll be catching and redirecting with apache. Certain legacy and patterns will be better caught this way.

**Comment by pgaudet** [comment]
Done
