### ISSUE TITLE
Update GO website to mention 'GO knowledgebase' rather than GO database or GO resource

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#375]
To match how GO is presented in the last grant and in the upcoming GO update paper, we need to update GO website to mention 'GO knowledgebase' rather than GO database or GO resource.

Thanks, Pascale

**Comment by suzialeksander** [comment]
Most pages have been changed.  One little niggle: URL of http://geneontology.org/docs/introduction-to-go-resource/ includes "resource".  @kltm is it ok to change the permalink and just pop the old address under the redirect_from ??

**Comment by kltm** [comment]
@suzialeksander That would be fine; we don't have to sweat links too much.

**Comment by suzialeksander** [comment]
I believe https://github.com/geneontology/geneontology.github.io/pull/387 will be the last mention of 'resource', once that's merged this can be closed

**Comment by suzialeksander** [comment]
Also adding https://github.com/geneontology/geneontology.github.io/pull/390
