### ISSUE TITLE
Fate of external2GO

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#39]
Moved from https://github.com/geneontology/go-docs/pull/27: 
Original post:
>If all CVS stuff is gone, is there only one way to access the mappings (http://geneontology.org/external2go/), or did I miss something

@pgaudet commented 
>kltm Is this the correct link for ? http://geneontology.org/external2go/ ?
Also, when will this be complete? http://release.geneontology.org/2018-10-01/ontology/external2go/index.html
Or are we not maintaining the other mappings ?
Thanks, Pascale

@kltm added 
>I believe that the fate of external2go is still under discussion.
tagging @cmungall

Now awaiting the return of @cmungall

**Comment by suzialeksander** [comment]
Just found that EBI links to this directly:

https://www.ebi.ac.uk/GOA/InterPro2GO

http://www.geneontology.org/external2go/interpro2go

... in case that matters.

**Comment by pgaudet** [comment]
Are we the only ones hosting these ? 
https://www.ebi.ac.uk/GOA/HAMAP2GO

@tonysawfordebi  Can you help ? How are these generated and how users use them ?

**Comment by tonysawfordebi** [comment]
We generate a number of external2go files and make them available at ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/external2go. We also currently still submit them to the GOC SVN repository.

The hamap2go file is derived from the data supplied by the UniProt automatic annotation (UniRule) team.

With regard to _how_ users use these external2go files, I have no idea. I've just checked the stats for our ftp site, and so far this year the total number of downloads of all of the external2go files is 738, so clearly somebody finds them useful, but for what I'm not sure...

**Comment by pgaudet** [comment]
Great, thanks @tonysawfordebi !

**Comment by lpalbou** [comment]
@cmungall @kltm how do you want to handle those files ? do you (want to) store them somewhere and have a nginx/apache redirect ?

**Comment by kltm** [comment]
Talking with @cmungall 
These are part of the release and are/will be handled at the server level.
