### ISSUE TITLE
large-datasets-curation-icon-mmt.png

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#41]
I need the images to be tweaked a little.  The one currently labelled "Large sets of data", http://geneontology.org/sites/default/files/u602/large-datasets-curation-icon-mmt.png
- can we rename/recaption this as "Annotations from large datasets" or something to match the other images? It's already not in line with the others, not sure how hard these are to tweak.

@lpalbou might know?

**Comment by pgaudet** [comment]
We dont want this image.
