### ISSUE TITLE
Remove mentions of reference BDbag

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#410]
@suzialeksander Poking around, the only change might be here
http://geneontology.org/docs/downloads/
removing
"Interested in a smaller or more flexible DOI versioned bundles? Holey (reference) BDBag available at [Zenodo - record 1205159](https://doi.org/10.5281/zenodo.1205159)"
We will still be getting DOIs and depositing in Zenodo (for the time being), but we are creating one less archive--the "reference" archive. Largely, we do not refer to it or have already removed documentation to it (it was mentioned in the bdbag stuff).

_Originally posted by @kltm in https://github.com/geneontology/pipeline/issues/269#issuecomment-1450863272_

**Comment by kltm** [comment]
See https://github.com/geneontology/geneontology.github.io/pull/418
