### ISSUE TITLE
Update PANTHER links/info

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#412]
Right now, list of supported species (in FAQ) goes to ftp, which isn't as helpful and could be a barrier to users.  Change to link to list on... pantherdb? maybe http://data.pantherdb.org/ftp/generic_mapping/archive/2022-05-25/stats

**Comment by pgaudet** [comment]
How about this one? 
http://www.pantherdb.org/panther/summaryStats.jsp

**Comment by suzialeksander** [comment]
thanks, I'll link that one, it's good for the main ~143 species.  

The main concern was the link supporting the claim of 770+ genomes, I'd like to be able to link to that Reference Proteome list so users could look/search more easily

**Comment by pgaudet** [comment]
Ha !! 

Check with @huaiyumi

**Comment by suzialeksander** [comment]
also on this topic- is the 2019 NAR still the correct PANTHER reference? There is a 2022 paper https://pubmed.ncbi.nlm.nih.gov/34717010/ @pgaudet

**Comment by suzialeksander** [comment]
all doneskis.
