### ISSUE TITLE
Hide/de-emphasise sparql endpoint 

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#449]
Per Managers meeting, we decided to hide or otherwise make it clear the sparql endpoint is not officially supported by GO.  Need to check/change documentation.

Possibly some useful info on  
https://github.com/geneontology/go-site/issues/1549 which links to  https://github.com/geneontology/go-site/issues/1606 &  https://github.com/geneontology/geneontology.github.io/issues/269

**Comment by kltm** [comment]
Also see:
https://github.com/geneontology/project-management/issues/70#issuecomment-1529053543
https://github.com/geneontology/project-management/issues/70#issuecomment-1529054609

**Comment by pgaudet** [comment]
Location where the SPAQRL end point is mentioned: 
https://geneontology.cloud/home 
https://geneontology.org/docs/sparql
https://geneontology.github.io/docs/tools-guide/

@suzialeksander Would you please remove the mention of SPAQRL in these pages? 

Thanks, Pascale

**Comment by kltm** [comment]
The ".cloud" one will need me or @dustine32, I believe.

I also have in my notes that people are finding and using this: https://app.swaggerhub.com/apis-docs/geneontology/gosparql/2.2 (so it may be linked _somewhere_. Also, I have a note that https://geneontology.org/docs/download-go-cams/ is confusing.

Finally, I have a note that I am to tag @kimrutherford when the ticket is made.

**Comment by kimrutherford** [comment]
> Finally, I have a note that I am to tag @kimrutherford when the ticket is made.

Thanks.  We have stopped using the SPAQRL end point.

**Comment by suzialeksander** [comment]
Other than https://github.com/geneontology/web-gocam/pull/26 which is awaiting @dustine32, direct links should be gone

We do have https://geneontology.org/sparql, not to be confused with https://geneontology.org/docs/sparql.html which has been cleaned. Should the /sparql page be completely eliminated?

**Comment by suzialeksander** [comment]
tagging @kltm about go.org/sparql, is this page being killed off (related to https://github.com/geneontology/geneontology.github.io/issues/267)? does that need a new specific ticket somewhere?

**Comment by kltm** [comment]
@suzialeksander While deprecating, I don't think we've pulled the trigger on full excision yet, which means that that page should still remain (for the moment).

**Comment by suzialeksander** [comment]
since not fully deprecated, this action is complete for now
