### ISSUE TITLE
Clarification needed for go-file-format-guide.md page

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#45]
This is probably a question for @kltm 
The bottom of this page is confusing: 

> ## Legacy file formats (no longer supported) 
> 
> ### OWL RDF/XML Format
> 
> OWL is a standard for ontology languages, produced by the W3C. Details of the translation used for GO is available on the official OboInOwl page.
> 
> ### Legacy Formats
> OBO-XML and FASTA files were retired in 2018.  

(Maybe Suzi and I tried to do changes at the same time). 

Do we mean simply: 

> ## Deprecated file formats (no longer supported) 
> OWL RDF/XML, OBO-XML and FASTA files were retired in 2018.  

? Thanks, Pascale

**Comment by kltm** [comment]
I think that while the latter is more clear in some ways, it leaves open that we have them, but do not support them. The former seems to communicate better to me that we simply do not have them. Maybe a hybrid:
```
Deprecated file formats:
The legacy format OBO-XML and FASTA files are no longer provided by the GO as of mid-2018.
```
Also note that we do provide OWL formats, XML for the ontology and TTL for annotations, but not OBO-XML, which was something different.
