### ISSUE TITLE
Create a page to describe taxon constraints

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#492]
Hi @suzialeksander 
QuickGO points to a broken page describing GO_REF:0000056 to describe taxon constraints. GO_REF:0000056 is obsolete but could contain useful information to make a page describing how the TCs work? 

https://github.com/geneontology/go-site/blob/master/metadata/gorefs/goref-0000056.md

+ we should explain what Taxon Unions are

Thanks, Pascale

**Comment by suzialeksander** [comment]
https://github.com/geneontology/geneontology.github.io/pull/498/commits
