### ISSUE TITLE
The SPARQL widget at https://geneontology.org/sparql points to insecure *http*://rdf.gene..

### ISSUE THREAD

**Issue by JervenBolleman** [geneontology/geneontology.github.io#494]
Instead of https://geneontology.org/sparql making it impossible to use in many browsers.

**Comment by kltm** [comment]
@suzialeksander Could you update `http://rdf` to `https://rdf` in geneontology.github.io? Specifically, I found it at:
```
./_site/docs/sparql.html
./_site/sparql.html
./_docs/sparql.md
./sparql.html
```
I'm not sure the relation here...

**Comment by kltm** [comment]
Thank you so much @suzialeksander !
@JervenBolleman Is this working better for you now?

**Comment by JervenBolleman** [comment]
Perfect this solves my issues :) very helpful to have this sparql endpoint available. Thank you for being so quick
