### ISSUE TITLE
collaborations.md: Keep or not ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#50]
https://github.com/geneontology/go-docs/blob/master/docs/_docs/collaborations.md

@thomaspd what do you think?

**Comment by lpalbou** [comment]
Personally, I would keep it. It gives some perspectives on the project, but I don't know how up-to-date this is.

**Comment by pgaudet** [comment]
I will edit it.

**Comment by kltm** [comment]
@pgaudet This was part of an early project within Drupal for highlighting associated projects and it now very very out-of-date. I would shelve this for now and start fresh, if that's what the PIs want.

**Comment by pgaudet** [comment]
OK - SynGO only for now 

@thomaspd
