### ISSUE TITLE
Fontawesome needs (?) to be updated

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#512]
I'm trying to use the existing fa for mastodon, with intentions to add linkedin/bluesky links.  The existing links in the header use fontawesome, and I've tried to add Mastodon but it leaves just a gap- my best guess is the 6 year old fa doesn't have the mastodon logo.  

I don't know how to update this, I'm assuming we're on the free tier but not sure of much else.

https://github.com/geneontology/geneontology.github.io/pull/511 is a result of the missing fa-mastodon

**Comment by suzialeksander** [comment]
@kltm would you know more about this?

**Comment by suzialeksander** [comment]
also noting https://fontawesome.com/icons/mastodon?f=brands&s=solid and the bluesky icon should be in the next fa release.

**Comment by kltm** [comment]
Okay, noting difference between Font Awsome Free and Font Awesome (https://github.com/FortAwesome/Font-Awesome).

Poking around briefly, we have "awesome" files at:
```
sjcarbon@moiraine:~/local/src/git/geneontology.github.io[master]$:) find . -name "*awesome*"
./_site/fonts/fontawesome-webfont.woff
./_site/fonts/fontawesome-webfont.woff2
./_site/fonts/fontawesome-webfont.ttf
./_site/fonts/fontawesome-webfont.svg
./_site/fonts/fontawesome-webfont.eot
./_site/css/font-awesome.min.css
./fonts/fontawesome-webfont.woff
./fonts/fontawesome-webfont.woff2
./fonts/fontawesome-webfont.ttf
./fonts/fontawesome-webfont.svg
./fonts/fontawesome-webfont.eot
./css/font-awesome.min.css
```
(I'm guessing the latter set gets copied to the former set?)

Poking around the css/ and font/ folders (a la https://github.com/FortAwesome/Font-Awesome/tree/6.x/css), there appears to be a lot of similarly named files, but they are not the same--likely they changed filenames and other things between versions, so it may not be a drop-in replacement.

So, the basic thing to do would be to use the FA standard "free" CSS and just make sure that the files it references are in the right place. Either the GH page or the download page (https://fontawesome.com/download, click "Free For Web"). Just copy those folders to the analog in our file tree and adjust the headers in the site:
```
sjcarbon@moiraine:~/local/src/git/geneontology.github.io/_includes[master]$:) isolate awesome
./head.html:11:    <link rel="stylesheet" href="{{ "/css/font-awesome.min.css" | prepend: site.baseurl }}">
```
^ looks like it might just be a change here.

And I'd do that all on a branch, in case you want to back out easily.

**Comment by suzialeksander** [comment]
@kltm it looks like newer versions want us to pick Webfonts+CSS or SVG+JS... do we have a preference?

**Comment by kltm** [comment]
While the latter sounds fun, the former sounds like it's likely more sane. That said, as I'm about to be out the door for a bit, I'm happy to defer to @pkalita-lbl, who would have a better idea where the easiest and most stable solution is at these days.

**Comment by pkalita-lbl** [comment]
Sure, no problem. If you want to assign this one over to me I'm happy to do the upgrade.

**Comment by pkalita-lbl** [comment]
I just remembered that @kltm is probably already out of the office. I'll go ahead and assign myself in that case.

**Comment by suzialeksander** [comment]
that would be great, thanks @pkalita-lbl
