### ISSUE TITLE
Feedback on gene-product-information-gpi-format-20.md 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#521]
Hi @suzialeksander 

I noticed a few inconsistencies between that new file and the GPAD2.0 file: 

- [x]  In the [GPAD 2.0  documentation file](https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md) we dont list the changes relative to the previous version; which is in the GH document (https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md); I dont mind which way we want to do this, but this should be the same (either the information should be included or not) 
- [x]  We should be using the same headers types for similar sections across both files (for GPAD and GPI) 
- [x]  We should copy more of the text of the beginning section of the [GPAD 2.0  documentation file](https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md) ; we worked on this a lot, and I think it reads better
- [x]  Header: we should have the same minimal requirements as for GPAD2.0: gpi-version, generated-by and date-generated
- [x]  "GAF fields" header: change to "GAF file fields" (to align with GPAD2.0 file)
- [x]  Definitions and requirements for field contents: subsections should be numbers as in the GPAD2.0 documentation
- [x]  "DB:DB_Object_ID": would could take the same text as in the GPAD2.0 documentation.
- [x]  In the GPAD2.0 documentation, the cardinality statement is always at the bottom of the description of the field, please make it the same way.
- [ ]  BTW, looks like cardinality is missing from the original specs? https://github.com/geneontology/go-annotation/blob/master/specs/gpad-gpi-2-0.md
- [ ] We can discuss reformulating some of the text, for example I dont think the gene naming guidelines under "DB_Object_Symbol" really belong here. If there is a general resource for this we can link, but really we want groups to submit the gene name. 

Thanks, Pascale

**Comment by suzialeksander** [comment]
I see cardinality is in the specs, just in BNF
