### ISSUE TITLE
New page / FAQ for Best practices for linking to GO entities

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#533]
Hi @suzialeksander 

@kltm provided some useful information as to how resources should link to GO: 
(in the context of the work to revamp GOREF system): 

Can you please add this information on the website (a page? addition to an existing page? FAQ?) 
Note that this is already in te FAQ page, updating that section is probably fine. 

----

Best practices for linking to GO entities

GO uses persistent uniform resource locator (PURLs) for all the objects it describes. The supported format for linking to GO stuff

GO terms: https://purl.obolibrary.org/obo/GO_0022008
GO_REFs: https://purl.obolibrary.org/obo/go/references/0000005 
GO-CAM models: https://model.geneontology.org/65c57c3400001018 
GO ontology (versions): 
current: https://purl.obolibrary.org/obo/go/go.owl 
snapshot: https://purl.obolibrary.org/obo/go/snapshot/go.owl
dated release: https://purl.obolibrary.org/obo/go/releases/2024-03-28/go.owl 

Technical documentation can be found here: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/README.md

----

Thanks, Pascale

**Comment by suzialeksander** [comment]
done
