### ISSUE TITLE
go-subset-guide.md has links to cvs

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#54]
Do we keep these links in:

http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/GO_slims/archived_GO_slims/
http://cvsweb.geneontology.org/cgi-bin/cvsweb.cgi/go/GO_slims/archived_GO_slims/generic.0208

etc (all old slims are linked to the same cvs site).

**Comment by lpalbou** [comment]
@kltm if the cvsweb subdomain is still maintained, I would keep these files for archival purpose at the moment and to be on the safe side

@pgaudet however, I would put this "outdated" section at the end of the page, so it appears less prominent

**Comment by kltm** [comment]
@pgaudet  
We will eventually try and glom all of the archives together, but for now we just have a lot of stuff nobody knows about. I would make a list of artifacts like this for the wiki (for reference and use if requested) and keep them out of the main documentation while we figure out what to do with them.

**Comment by pgaudet** [comment]
These cvs links are gone :)
