### ISSUE TITLE
contributing-go.md: replace images by just header ? 

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#55]
I dont think the images here are particularly informative: 
https://github.com/geneontology/go-docs/blob/master/docs/_docs/contributing-go.md

**Comment by pgaudet** [comment]
Never mind I was not looking at the right thing. 


The links on this page are broken, I think Suzi mentioned that. 

Thanks, Pascale

**Comment by lpalbou** [comment]
Nop, they are not, you can test them here: http://test-gosite.s3-website-us-west-1.amazonaws.com/docs/contributing-to-go/

They just appear broken on the GH preview of the page and it's related to my yesterday email on renaming this repo (or copying it) to geneontology.github.io repo. Once we have transfer to that repo, you will be able to see your live modifications on http://geneontology.github.io (which contains an old and unused mockup)

**Comment by pgaudet** [comment]
Removed images
