### ISSUE TITLE
Update ttl files link in the GO-CAM page of the GO website

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#561]
Here: https://geneontology.org/docs/download-go-cams/

Please update the link to 
/products/ttl/pathway-like_go-cams.tar.gz

@kltm

**Comment by pgaudet** [comment]
Noting that this is only the 'connected' GO-CAMs

Maybe worth announcing? and improve documentation.

**Comment by suzialeksander** [comment]
@kltm is this ticket saying to change the link for [GO-CAM TTLs] which was https://s3.amazonaws.com/geneontology-public/gocam/GO-CAMs.ttl.zip)
to current.geneontology.org/products/ttl/pathway-like_go-cams.tar.gz? 

Should I leave the existing link and make a note this new link is for pathway-like gocams, or are we trying to eliminate the aws links?

**Comment by kltm** [comment]
As a general rule, any link that's not to an "official" product (i.e. in current.geneontology.org) should be eliminated.
For this specific case, the link should be updated to current.geneontology.org/products/ttl/pathway-like_go-cams.tar.gz, with an explanatory note like: "Pathway-like GO-CAMs". We should probably work out how best to explain that; essentially: https://github.com/geneontology/pipeline/issues/376#issue-2284358378 .
