### ISSUE TITLE
Reindex site in Algolia (Oct 2024 edition)

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#605]
Requesting the search be reindexed. Noting previous complications and likely need to exclude the following: 
- gorefs.html
- GO_REF/0000012.html
- GO_REF/0000024.html

(last attempt was https://github.com/geneontology/geneontology.github.io/issues/574 and none of those issues should matter here either)

**Comment by kltm** [comment]
Thank you @suzialeksander 

As before, highlighting https://github.com/geneontology/geneontology.github.io/issues/575

**Comment by kltm** [comment]
@suzialeksander The indexing should be complete. Oddly, I got no error message this time and "everything" may have been indexed. Which is odd to me. Have you removed pages or has anything been "repackaged" since the last time?

**Comment by suzialeksander** [comment]
Although we've removed some pages as far as "no longer linked in obvious places", nothing substantial has been removed and all the  same pages should pretty much be indexed. Maybe limits were changed on the algolia end? If anything, the pages should be bloatier because of added images that previously were in the repo but not linked in the website.
