### ISSUE TITLE
Edit text contributing-go.md

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#65]
http://geneontology.org/docs/contributing-to-go/
Edit the annotations - not the ontology

**Comment by pgaudet** [comment]
@suzialeksander Were you working on this page ? 
The text looks jumbled - let me know if you want me to look or if you were doing this as part of the 'external contributions' documentation. 

Thanks, Pasclae

**Comment by suzialeksander** [comment]
@pgaudet Yes, this most certainly is in progress.  I'll re-arrange some of the new "how to contribute (NEW)" category we made earlier today; some of this will also go to the wiki (but isn't written anywhere else yet so don't delete too much, adding/moving is fine).

**Comment by lpalbou** [comment]
@suzialeksander any update on that ?

**Comment by suzialeksander** [comment]
@pgaudet I think some pages need our attention more than this one, can I close this? I think the "contact us to make new annotations" covers us for now, until we can decide on a protocol.

**Comment by lpalbou** [comment]
I just merged this PR for the [contributing-to-go-terms](http://geneontology.org/docs/contributing-to-go-terms/) page: https://github.com/geneontology/geneontology.github.io/pull/164

And did a quick commit to have something equivalent for the [contributing-to-go](http://geneontology.org/docs/contributing-to-go/): https://github.com/geneontology/geneontology.github.io/commit/0803a29802d2cb0126c2a28aa1de9739b29d899b

Before closing this ticket, we need to better link those pages: only the [contributing-to-go-terms](http://geneontology.org/docs/contributing-to-go-terms/) is linked from [ontology-documentation](http://geneontology.org/docs/ontology-documentation/), but there is no link to [contributing-to-go](http://geneontology.org/docs/contributing-to-go/) in [go-annotations](http://geneontology.org/docs/go-annotations/)

**Proposal**: add a link to contribute to [contributing-to-go](http://geneontology.org/docs/contributing-to-go/) in [go-annotations](http://geneontology.org/docs/go-annotations/)

**Comment by pgaudet** [comment]
> Proposal: add a link to contribute to contributing-to-go in go-annotations


Please go ahead.

**Comment by lpalbou** [comment]
Done: https://github.com/geneontology/geneontology.github.io/commit/3be34144c295d2817f2442f6d320c384d9009b24
