### ISSUE TITLE
Download annotation table needs to be sorted by organism, not group- other glaring issues

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#85]
- [ ] The table that allows users to access annotations (bottom of  geneontology.github.io/_docs/download-go-annotations.md, which links to http://current.geneontology.org/products/pages/downloads.html)

is currently sorted by the group (MGI, etc.) not by organism (mouse), and doesn't necessarily have a human-recognisable name.  Currently says  
>dictyBase (dictybase, Ddis)

Should perhaps be 
>*Dictyostelium discoideum* (maintained by dictybase)

- [ ]  n/a should be "GENE", no?

- [ ] "File" header should say 'GAF', and additional columns for GPAD and GPI should be added (to match what's available and current documentation

probably @kltm @lpalbou @thomaspd know something about this discussion, or if this is an existing/related to a https://github.com/geneontology/pipeline/issues?

**Comment by kltm** [comment]
Discussing here is fine, but the mechanism does indeed live somewhere else.

**Comment by suzialeksander** [comment]
@kltm So if we need these changes made, where do I move this issue? Thanks!

**Comment by kltm** [comment]
Is these are changes that need to be made, rather than discussion points, these items can be broken up into separate tickets in `go-site`, as that's where the generation scripts live.

Name question: isn't GPA + GPI = GPAD, or have the names shifted again?

**Comment by suzialeksander** [comment]
Thanks!

**Comment by lpalbou** [comment]
@kltm pinging you here. As those tickets been created on go-site ? Could you send the link to the current code generating this download file ? Thanks

**Comment by kltm** [comment]
Duped by https://github.com/geneontology/go-site/issues/846
