### ISSUE TITLE
Zotero section in go-citation-policy/

### ISSUE THREAD

**Issue by pgaudet** [geneontology/geneontology.github.io#87]
Is this current ? Are we using Zotero? How ?

**Comment by kltm** [comment]
Was working with @suzialeksander , but still getting off the ground:
https://www.zotero.org/groups/296432/gene_ontology
This is an attempt at replacing the scripts and maintenance that Amelia handled a couple of site iterations ago. 
We probably don't want to have this public yet.

**Comment by pgaudet** [comment]
I'll remove from now. 

Thanks Pascale
