### ISSUE TITLE
Save images to geneontology.github.io/assets/

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#91]
Image on http://geneontology.org/page/ontology-structure needs to be saved, and if it's quick we'd like to include a few from http://geneontology.org/page/ontology-relations, so save all of those and we'll delete the ones we don't use (if it's time consuming, save first 4 and we'll talk about the rest later).

Thanks

**Comment by pgaudet** [comment]
Who is doing this ?

**Comment by lpalbou** [comment]
PR merged with 43 images: https://github.com/geneontology/geneontology.github.io/pull/93

To show them:
`![description](/assets/diag-ontology-graph.gif)`

If you need to center them horizontally:
`![description](/assets/diag-ontology-graph.gif?style=center)`

**Comment by lpalbou** [comment]
I will let you close this ticket if everything is ok.

**Comment by suzialeksander** [comment]
I think this is OK; I'd like to leave this open until we've added images (just to remind me/us that it needs to be done)

**Comment by lpalbou** [comment]
@suzialeksander it's been some time now, are there any more images to add or can we close this ticket ?

**Comment by suzialeksander** [comment]
hey @lpalbou, I was trying to add a twitter logo to make a button and they're loading as, well, they're not working.  Can you try? I downloaded images from https://about.twitter.com/en_us/company/brand-resources.html (I tried the "social icons" and the "twitter logo"; "social icons" is what I want if there's a choice).

I see now I was trying to put them in geneontology.github.io/img/ instead of /assets/, but I don't think that is the cause for my issues.

Can you try and load these twitter PNGs?

thanks

**Comment by lpalbou** [comment]
@suzialeksander it doesn't really matter which folder you use, although I would argue of using only the /assets/ and I'll remove later the /img where we only have a few images.

Anyhow, I have added your image in /assets/Twitter_Logo_Blue.png

So you can reference it from a markdown page as 
```
![mini logo](/assets/Twitter_Logo_Blue.png)
```

Let me know if you have to include others but you should not have had any problem adding those.

**Comment by suzialeksander** [comment]
OK, it looks like I may not need these but thanks for the info.
