### ISSUE TITLE
Overall formatting- top nav bar gets too bulky

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/geneontology.github.io#92]
With the current top nav menu, if the font size is slightly too big the menu sort of collapses and takes up far too much space.  It also partially covers headings and the side nav bar.  My window is filling up 75% of a 15" screen, thinking of users on smaller screens/tablets or with worse eyesight than mine.

Proposal: Leave the logo but take "Gene Ontology Resource" out of the nav bar??? Possibly other options too of course.
@lpalbou 

![menutoobig](https://user-images.githubusercontent.com/13735608/46565274-6c3dcc00-c8c2-11e8-9655-face9b62b96e.jpeg)

**Comment by lpalbou** [comment]
This will be corrected with the new design of the site (see first pass here: https://github.com/geneontology/geneontology.github.io/pull/94)
